tenant: "public"
namespace: "document"
name: "extractor-eventos-documentos"
topicName: "persistent://public/document/fallback"
archive: "connectors/pulsar-io-debezium-postgres-4.1.3.nar"

configs:
    ## --- CONNECT ---
    database.hostname: "172.17.0.1"
    database.port: "5432"
    database.user: "postgres"
    database.password: "password"
    database.dbname: "api_document"
    database.server.name: "dbserver1"
    

    table.include.list: "public.events"
    plugin.name: "pgoutput"

    transforms: "outbox"
    transforms.outbox.type: "io.debezium.transforms.outbox.EventRouter"
    
    transforms.outbox.route.by.field: "entity_type"
    transforms.outbox.route.topic.replacement: "persistent://public/document/${routedByValue}"
    
    transforms.outbox.table.field.event.key: "entity_id"
    
    transforms.outbox.table.field.event.payload: "data"
    
    transforms.outbox.table.expand.json.payload: "true"

    database.history: "org.apache.pulsar.io.debezium.PulsarDatabaseHistory"
    database.history.pulsar.topic: "persistent://public/document/history-topic"
    database.history.pulsar.service.url: "pulsar://localhost:6650"
    offset.storage.topic: "persistent://public/document/offset-topic"
    pulsar.service.url: "pulsar://localhost:6650"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"
    value.converter.schemas.enable: "false"